### ISSUE TITLE
Use public a2a-sdk instead of local

### ISSUE THREAD

**Issue by rgstephens** [theailifestyle/mas-a2a#1]
Thanks for the repo and blog post.

Remove references to local `a2a-sdk`

```toml
[tool.uv.sources]
a2a-sdk = { workspace = true }
```
